Document: fern-wifi-cracker
Title: Debian fern-wifi-cracker Manual
Author: <insert document author here>
Abstract: This manual describes what fern-wifi-cracker is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fern-wifi-cracker/fern-wifi-cracker.sgml.gz

Format: postscript
Files: /usr/share/doc/fern-wifi-cracker/fern-wifi-cracker.ps.gz

Format: text
Files: /usr/share/doc/fern-wifi-cracker/fern-wifi-cracker.text.gz

Format: HTML
Index: /usr/share/doc/fern-wifi-cracker/html/index.html
Files: /usr/share/doc/fern-wifi-cracker/html/*.html
